### ISSUE TITLE
How to extend mxGraph classes?

### ISSUE THREAD

**Issue by awesomenkj** [lgleim/mxgraph-typings#11]
![image](https://user-images.githubusercontent.com/30191792/72432875-fa9f2f80-374c-11ea-8773-3f83b85dbdd3.png)

`// Overrides zIndex for dragElement
      mx.mxDragSource.prototype.dragElementZIndex = mx.mxPopupMenu.prototype.zIndex;`

How to extend mxGraph classes? I tried the above method. But it doesn't work.

**Comment by lgleim** [comment]
This is really a TypeScript question rather then a question related to this project. 

Refer e.g. to https://www.pluralsight.com/blog/software-development/extending-classes-and-interfaces-using-typescript
